# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Locally build the release APK"
  lane :local_build do
    gradle(
      task: "assembleRelease",  # Assembles the release APK
      project_dir: "./"
    )
  end

  desc "Build debug APK and install on connected device"
  lane :run_local do
    gradle(
      task: "assembleDebug",
      project_dir: "./"
    )
    sh "adb install -r app/build/outputs/apk/debug/app-debug.apk"
  end
end


