name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the OS for GitHub runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # The version of JDK you want to use
          distribution: 'adoptopenjdk'  # Distribution name (adoptopenjdk, temurin, etc.)

      - name: Install dependencies and run tests
        run: ./gradlew build test  # Runs build and tests using Gradle

      - name: Build the project
        run: ./gradlew build  # Builds the project

      - name: Deploy to Vercel
        run: |
          curl -s https://vercel.com/download > vercel-cli.deb
          sudo dpkg -i vercel-cli.deb
          vercel --prod  # Deploy to Vercel

      - name: Deploy to Render
        run: |
          curl -fsSL https://cli.render.com | bash
          render deploy --prod  # Deploy to Render
