name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build app
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Deploy to Vercel
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel deploy --prod --yes --token=$VERCEL_TOKEN

    - name: Deploy to Render
      if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
