name: Android CI

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java 17)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Using the Temurin JDK distribution
          java-version: '17'  # Java version 17

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'  # Specify the SDK version, adjust if needed

      # Step 4: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./
