name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on main branch push (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Use your desired Java version
        distribution: 'temurin'  # Use Adoptium distribution

    - name: Install dependencies
      run: ./gradlew build  # Adjust depending on your build tool (e.g., Gradle or Maven)

    - name: Run unit tests
      run: ./gradlew test  # Adjust this for your test framework (e.g., JUnit, TestNG)

    - name: Build application
      run: ./gradlew build  # Adjust based on your build tool

    - name: Deploy to Vercel
      run: |
        curl -s https://vercel.com/download > vercel-cli.deb
        sudo dpkg -i vercel-cli.deb
        vercel --prod  # Adjust as necessary for your Vercel setup

    - name: Deploy to Render
      run: |
        # Similar steps to deploy to Render, adjust accordingly
        curl -fsSL https://cli.render.com | bash
        render deploy --prod
