name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on main branch push (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  
        distribution: 'temurin'  

    - name: Install dependencies
      run: ./gradlew build  

    - name: Run unit tests
      run: ./gradlew test  

    - name: Build application
      run: ./gradlew build  

    - name: Deploy to Vercel
      run: |
        curl -s https://vercel.com/download > vercel-cli.deb
        sudo dpkg -i vercel-cli.deb
        vercel --prod  # Adjust as necessary for your Vercel setup

    - name: Deploy to Render
      run: |
        # Similar steps to deploy to Render, adjust accordingly
        curl -fsSL https://cli.render.com | bash
        render deploy --prod
